make_logs: true
comment: "Percentile clipping for tensors_nG"

opt:
  device: 3
  criterion: "SFL" #"Unified"
  delta: 0.999 # 0.5
  gamma: 0 # 0.6
  weight: 0.5 # for USFL
  # grad_clip: 1
  use_scaler: false

  start_epoch: 0
  n_epochs: 9999

  augmentation: true #true

  train_batch_size: 1
  val_batch_size: 1

  lr: 0.001
  save_model: true
  
model:
  name: "v2v" 
  output_channels: 1 
  max_channel_encoder_decoder: 128 
  sigmoid: true
  normalization: 'instance_norm' #'group_norm'
  activation: 'LeakyReLU'
  use_greedy_saving: false
  target_metric_name: 'dice_score'

dataset:
  save_best_val_predictions: true
  trim_background: true  
  patch_overlap: 0.8
  
  features: ['curv', 'sulc', 'thickness', 'bT1', 'bT2', 'T1w', 'CSF', 'GM', 'WM', 'cr', 'entropy'] 
  add_xyz: true
  # predictions_path: '/nfs/tom/ibulygin/FCDNet/logs/logs_nG/v2v128-IN_s128_bs1_GN_SFL-d0.9-g2-lr1e-3_nG-AUG-autocast@04.05.2022-19:53:34/predictions'
  root: '/mnt/tom/ibulygin/fcd_data/tensors_nG' # chng tp /mnt/... for ws-*
  metadata_path: 'metadata/metadata_fcd_nG.npy'
  dataset_type: 'fcd'

  # features: ['t1', 't1ce', 't2', 'flair']
  # root: '/nfs/tom/ibulygin/fcd_data/brats2020_tensors'
  # metadata_path: 'metadata/metadata_brats2020.npy'
  # dataset_type: 'brats'

  sampler_type_train: 'balanced' #'balanced'
  sampler_type_val: 'grid'
  
  label_ratio: 0.5
  patches_per_brain: 500
  patch_size : 64
  shuffle_train: false
  patch_batch_size : 6
