make_logs: true
interpolate: true
interpolation_size: [128, 128, 128] 
silent: false

opt:
  device: 1
  criterion: "DiceBCE" # "Dice" 
  bce_weights: 250
 
  start_epoch: 0
  n_epochs: 9999

  augmentation: true

  train_batch_size: 1
  val_batch_size: 1

  lr: 0.001  
  save_model: true

model:
  name: "v2v" 
  output_channels: 1 # FCD and background
  max_channel_encoder_decoder: 128 
  sigmoid: true
  normalization: 'group_norm'
  use_greedy_saving: false
  target_metric_name: 'dice_score'

dataset:
  save_best_val_predictions: true
  trim_background: true  
  features: ['curv', 'sulc', 'thickness', 'bT1', 'bT2', 'T1w', 'CSF', 'GM', 'WM', 'cr', 'entropy'] 
  root: '/nfs/tom/ibulygin/fcd_data/tensors_MNI152'
  
  # metadata_path: 'metadata/metadata_fcd_nG.npy'
  # root: '/nfs/tom/ibulygin/fcd_data/tensors_orig'
  metadata_path: 'metadata/metadata_fcd.npy'
  dataset_type: 'interpolated'
