make_logs: true
 
opt:
  device: 0
  criterion: "BCE" 
  
  start_epoch: 0
  n_epochs: 9999

  augmentation: true

  train_batch_size: 32
  val_batch_size: 32

  lr: 0.0005 # default - 0.0001 
  save_model: true

model:
  classification_threshold : 0.5

dataset:
  fcd_threshold: 0.8
  augmentation_steps: 2
  features: 'ALL' #'ALL'
  root: '/nfs/garfield/ibulygin/tensors_v2'
  patch_size : 32
  
