make_logs: false

opt:
  device: 0
  criterion: "BCE"  
 
  start_epoch: 0
  n_epochs: 9999

  augmentation: true

  train_batch_size: 1
  val_batch_size: 1

  lr: 0.001 # default - 0.0001 
  save_model: true
  use_greedy_saving: false
  target_metric_name: 'dice_score'

model:
  classification_threshold : 0.5

dataset:
  trim_background: true  
  features: 'ALL' 
  # root: '/nfs/tom/ibulygin/MICCAI_BraTS2020_TrainingData' 
  root: '/nfs/garfield/ibulygin/tensors_v2'
  metadata_path: '/nfs/garfield/ibulygin/metadata_v2.npy'
  dataset_type: 'patches_tio'
  sampler_type: 'grid'
  patch_size : 32
  shuffle_train: false
  patch_batch_size : 16
  top_k_list: [10, 50, 100]
  patch_fcd_threshold: 0.5
  