experiment_dir: './logs'
interpolate: true
interpolation_size: [128, 128, 128] 
make_logs: true
silent: false

opt:
  device: 1
  criterion: "BCE" 
  task: "segmentation"
  prob_threshold: 0.5
 
  start_epoch: 0
  n_epochs: 9999

  train_batch_size: 1
  val_batch_size: 1

  lr: 0.0005

  save_model: true

model:
  name: "v2v" 
  output_channels: 1 # FCD and background
  max_channel_encoder_decoder: 32
  sigmoid: true

dataset:
  use_features: true
  trim_background: true
  features: ['thickness', 'sulc', 'curv']
  root: '../fcd_data/normalized_tensors' 
  # root: '../fcd_data/patches_dataset_64_features'
  dataset_type: 'interpolated'
  # dataset_type: 'patches'
  patch_size: 64
