experiment_dir: './logs'
interpolate: true
interpolation_size: [128, 128, 128] 
make_logs: true
silent: false

opt:
  device: 2
  criterion: "Dice" 
 
  start_epoch: 0
  n_epochs: 9999

  augmentation: true

  train_batch_size: 1
  val_batch_size: 1

  lr: 0.001 # default - 0.0001 
  save_model: true

model:
  name: "v2v" 
  output_channels: 1 # FCD and background
  max_channel_encoder_decoder: 32
  sigmoid: true
  normalization: 'group_norm'
  # weights: 'logs/v2v_whole_BRATS-all_s128_bs1_GN_DICE_AUG@11.12.2021-02:13:57'
  # weights: 'logs/v2v_whole_BRATS-all_s128_bs1_GN_DICE@10.12.2021-17:26:10/'

dataset:
  use_features: false
  trim_background: true  
  features: ['thickness', 'sulc', 'curv']
  root: '../fcd_data/normalized_tensors' 
  # root: '../MICCAI_BraTS2020_TrainingData'
  # root: '../fcd_data/patches_dataset_64_features'
  # root: '../fcd_data/data_only_usefull_areas/full/' 
  # dataset_type: 'brats_interpolated'
  dataset_type: 'interpolated'
  # indexes_selected_root: '../fcd_data/indexes_selected_P0.9_L1250'
  # dataset_type: 'patches'
  # patch_size: 64
