distributed_train: false # not working
experiment_dir: './logs'
interpolate: false
interpolation_size: [64, 64, 64]  #[91,109,91]
make_logs: true
silent: false

opt:
  criterion: "CE"

  start_epoch: 0
  n_epochs: 9999
  dump_weights: False

  train_batch_size: 10
  val_batch_size: 10

  lr: 0.0001

  save_model: true
  grad_clip: 0.01


model:
  name: "v2v" 
  input_channels: 1
  output_channels: 1
  max_channel_encoder_decoder: 32



dataset:
  root: '../fcd_data/patches_dataset_64_features'
  dataset_type: 'patches'
  patch_size: 64